# -*- coding: utf-8 -*-
"""deploy.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13d3_o0rWdOrVTiCdtwph3-tYdNC_PMAw
"""

from flask import Flask,render_template,request
import pickle

app=Flask(__name__)
model=pickle.load(open('savedmodel','rb'))

@app.route('/')
def home():
  return render_template('index.html')
@app.route('/predict',methods=['POST'])
def predict():
  Sepal_lenth=request['sepal_lenth']
  Sepal_width=request['sepal_width']
  petal_lenth=request['petal_lenth']
  petal_lenth=request['petal_width']
  result=model.predict([[Sepal_lenth,Sepal_width,petal_lenth,petal_lenth]])[0]
  return render_template('index.html',**locals)
  


if __name__=="__main__":
  app.run(debug=True)

